### ISSUE TITLE
Agenda item card 

### ISSUE THREAD

**Issue by adamcee** [hackla-engage/engage-client#27]
Working proto/mvp of Agenda item card: 

Agenda item card (scraped from council website) User reads/scrolls through Recommended Action and Executive Summary, clicks “Take Action” button that goes to vote form.

https://docs.google.com/document/d/19YzAdn1bi2khqk13Cd7qVs9g7KHhuEPIOLdJVfltxcI/edit

**Comment by EzDesigns** [comment]
AS A user
I WANT see a card with agenda item information on it
SO THAT I can know if I'm interested in the information that I see

GIVEN I see a card that I am interested in 
WHEN I click the card (buttons on the card)
THEN I am take to the full agenda
![agenda feed_mvp](https://user-images.githubusercontent.com/30360266/39728709-31db3222-520d-11e8-9910-bc5a30d0ea1a.png)

**Comment by dorachan2000** [comment]
same content on #41
