### ISSUE TITLE
Mobile - Item Card page

### ISSUE THREAD

**Issue by danielbaruch** [hackla-engage/engage-client#41]
**User Story:**
As a Santa Monica Resident, I want to select one of the Item Cards and view more details relating to the  Santa Monica City Council Members current Item, so that I may be educated on the specific Item that the Santa Monica City Council Members are reviewing.

**Notes:**
1. Fields to have included on the Item Card details are:
- Hearing Time
- Hearing Date
- Item Card Title
- Item Card Details (including "Executive Summary" and "Recommendation")

**Acceptance Criteria:**
1. The Santa Monica Resident installs the app
2. Opens the App
3. Lands on the Landing Page, selects the button at the bottom of the page
4. Lands on the Items feed
5. Select an Item Card from the Items Feed
6. New page opens with Item Card details including:
- Hearing Time
- Hearing Date
- Item Card Title
- Item Card Details

7. ~~[x] Item Card contains a “cancel” or “back” button which will close the card and return the user to their previous screen (the Items Feed). Tracking this in #62``~~

**Questions:**
1. @danielbaruch is asking - What are the details we would like displayed to the User? - 
2. @danielbaruch is asking - How would we like the User to vote on the issue? - 

**Attachments:**
![mvp item card](https://user-images.githubusercontent.com/30360266/39907356-165912a2-549d-11e8-9707-dac97294295f.png)

**Comment by EzDesigns** [comment]
We have decided to lean out the design on the card features. We will only give users the ability to **View Item** for the MVP

**Comment by dorachan2000** [comment]
@EzDesigns @danielbaruch When you change designs and specs, can you let others know and update the mocks in zeplin?

**Comment by adamcee** [comment]
FYI @danielbaruch @EzDesigns @dorachan2000 I just played with the live demo and some sort of back/cancel button is needed when viewing an individual item so if the user wants they can return to the feed without doing anything. Since the feature is, in terms of behavior, very small and self, contained, I’m going to create a different Issue for it and link to it in this main one. That way someone can tackle it independent of the larger feature.
